### ISSUE TITLE
Py-ART Grid refactor. 

### ISSUE THREAD

**Issue by jjhelmus** [nguy/artview#108]
I'm planning on a large refactor and reorganization of the **Grid** class in Py-ART and want to check on how much ARTView depends on the organization of the class.  If needed it should be possible to keep a compatibility layer which allow access to the old **Grid** attributes but if this is not needed I would like to avoid it.

**Comment by nguy** [comment]
I think @gamaanderson can answer better, but it looks like axes information is the most used part of the **Grid** class in ARTView. What kind of changes are you considering?

We could probably write a check upon a **Vgrid** initialization that checks attributes to account for changes.

**Comment by gamaanderson** [comment]
There is no need for a compatibility layer, we can copy the current version of `artview/components/plot_grid.py` to a new file and check pyart version while loading. All other uses of grid outside this file should not be dependent of any internal organization of grid (**thanks to artview's code independence model!**). Just inform us later which is the version to check for.

**Comment by jjhelmus** [comment]
Good to hear.

I'll outline the new layout I have in mind for the **Grid** object in ARM-DOE/pyart#285 tomorrow to gather feedback before implementation.  I have it drawn out on paper but have not had the time to write it up nicely.
