### ISSUE TITLE
Modes separation

### ISSUE THREAD

**Issue by nguy** [nguy/artview#120]
As discussed in Issue #117 it may be worth splitting modes into categories later on. This is to remind us to revisit this topic in the future.

**Comment by nguy** [comment]
Following a comment in PR #142 adding separator lines in the Modes Menu could help in splitting into categories.

Also, I think we should add a separator line and move Close to the bottom in Files menu.

**Comment by nguy** [comment]
Okay, we didn't do this in #142 b/c I forgot about it. I propose the following separation under the Modes Menu:
```
Add RadarDisplay
Add GridDisplay
Edit Colormap (Radar)
Edit Colormap (Grid)
----------------------
Map Radar to Grid
---------------------------
Apply Corrections to Radar
Apply Filter to Gates
Apply Filter to data
Manually unfold Velocity
---------------------------
Query a Selectable Region of Interest
Extract a Selected Region of Points
```

**Comment by gamaanderson** [comment]
ok thank you, I will adress this sometime in the near future

**Comment by nguy** [comment]
What are you working on next?

**Comment by gamaanderson** [comment]
in my list there is the layout and the background map, but those are long time tasks.

**Comment by nguy** [comment]
Okay great! Let me look at my task list again in the next couple of days and let you know what I'm going to work on.

**Comment by gamaanderson** [comment]
can this be closed?

**Comment by nguy** [comment]
Yes
