### ISSUE TITLE
Change in LinkPlugins

### ISSUE THREAD

**Issue by gamaanderson** [nguy/artview#127]
what do you think about this
![figure1](https://cloud.githubusercontent.com/assets/7915525/12840945/b2c2a478-cbe7-11e5-8dfa-dcaa8686467a.png)

I particularly find if ugly, but it is more verbose.

**Comment by gamaanderson** [comment]
or may be this

![figure2](https://cloud.githubusercontent.com/assets/7915525/12845628/8cc84e24-cc07-11e5-880a-25e182550f7b.png)

**Comment by nguy** [comment]
I would say the second image with "from *dropdown1*'  and 'to *dropdown2*' moved to the top of the page then this would have two columns and be more straightforward.

**Comment by gamaanderson** [comment]
The reason I make like this, is that it is supposed to be a phrase 
`limits from Display1 is linked to Display2` 

if I make

    from Display1
    to Display2
    limits   |  is linked

this idea get lots, don't it?

**Comment by nguy** [comment]
It could be something like:
```
Linking from Display1     to Display2
            limits                |  is linked
```

**Comment by gamaanderson** [comment]
ok now I understand, I will try to see how it looks

**Comment by gamaanderson** [comment]
it this it?
![figure3](https://cloud.githubusercontent.com/assets/7915525/12857938/475ff080-cc4d-11e5-86e6-fc847e3d8956.png)

**Comment by nguy** [comment]
I think that is much more straightforward. @tjlang @pfhein what do you guys think?

**Comment by pfhein** [comment]
Yes, I like the latest version. To nitpick, `Linking from Display1 to Display2` makes it sound like the linking only goes one way.  Would `Display1 linked to Display2` be better? Or something else?

**Comment by gamaanderson** [comment]
the linking process in not only one way, but it is asymmetrical:

initially `Display1` has `value1` and `Display2` has `value2`
one of those must go away, in this case `value1` is lost and `Display1` will end with `value2`.

**Comment by pfhein** [comment]
Yes, but how to say that. Maybe another way to say it is `Display1 and Display2 linked together` or maybe better just say `Display1 and Display2 Shared Variables` and below you can see which ones are linked.

**Comment by gamaanderson** [comment]
I choose the use of preposition to emphasize that
`from Display1 to Display2`
is not the same as
`from Display2 to Display1`

**Comment by pfhein** [comment]
Okay - I am being just dense.   Asymmetrical means asymmetrical.  Sorry!  Your wording then makes more sense.

**Comment by gamaanderson** [comment]
I added a help button. 
![figure5](https://cloud.githubusercontent.com/assets/7915525/12868317/1fae5b1e-cd04-11e5-8e37-ea316b5dc07c.png)

**Comment by nguy** [comment]
Nice, that provide some good help I think.
