### ISSUE TITLE
Aspect Ratio Option

### ISSUE THREAD

**Issue by stechma2** [nguy/artview#138]
If possible, it would be very useful to add an aspect ratio adjustment into the display options. In particular, I work with tail radar data primarily, and the default aspect ratio produces a very "squished" display which can be difficult to interpret.

**Comment by gamaanderson** [comment]
ok, that can be an easy add. Can you post one image,  so that I have an better idea on how that is showing up to you?

**Comment by gamaanderson** [comment]
but before that, have you tried "adjust display limits"? I know it is not optimal, but this should be able to unsquish your image.

**Comment by stechma2** [comment]
Here is the image with the default aspect ratio, and display limits set to incorporate the entire observable domain:
<img width="872" alt="screen shot 2016-03-21 at 2 06 19 pm" src="https://cloud.githubusercontent.com/assets/6628522/13931000/57d6087e-ef6f-11e5-96d3-97b4ffd69a41.png">
Here is the same image, with the same display limits, but with aspect ratio set to 1 
(using this hard coded addition to `plot_radar`): `self.display.set_aspect_ratio(aspect_ratio=1,ax=self.ax)`
<img width="872" alt="screen shot 2016-03-21 at 2 09 03 pm" src="https://cloud.githubusercontent.com/assets/6628522/13931062/9b368f94-ef6f-11e5-8e48-55c8ef848d61.png">
And finally, an image using the default aspect ratio, but adjusting the display limits and panning to unsquish and center the data. This method works, but is not ideal.
<img width="872" alt="screen shot 2016-03-21 at 2 13 35 pm" src="https://cloud.githubusercontent.com/assets/6628522/13931120/d15ffcc2-ef6f-11e5-8528-60771222423d.png">

**Comment by gamaanderson** [comment]
Ok, I see the difference, I will implement right away.

**Comment by gamaanderson** [comment]
I just submitted a PR for that. The aspect radio can be found in the adjust limits.

thank you again @stechma2 for helping improving ARTView.

**Comment by stechma2** [comment]
Great! Thank you for doing this @gamaanderson.

**Comment by nguy** [comment]
Tangentially, I finally figured out why the file does not come up with the default Airborne x/y ranges. The *scan_type* value of the radar variable is not recognizing these particular files as airborne. I have a workaround that I'll comment on in the PR. We'll have this out in the very near future with this fix.

**Comment by nguy** [comment]
Fixed with merge of PR #140
