### ISSUE TITLE
Keep user entered Nyqvist velocity

### ISSUE THREAD

**Issue by bdolan44** [nguy/artview#146]
We have found that when unfolding velocities, if you enter a Nyqvist velocity to unfold around, it is immediately reset to 0 as soon as you push a button to unfold, set up a boundary, etc. It would be great if the user entered value could remain. (This may only be a problem if the Nyqvist velocity is not in the radar file.)

**Comment by nguy** [comment]
Thanks @bdolan44 we'll look into this. @gamaanderson can you take a look or do you want me to? I would guess it would be just retrieving the entered value and caching it in a class variable?

**Comment by gamaanderson** [comment]
yes, the trick is to know when to use the variable and when to reset

**Comment by nguy** [comment]
When the button is clicked to perform the operation, then we could grab the values entered and update?

**Comment by gamaanderson** [comment]
and file change / field change?

**Comment by nguy** [comment]
yep, I think we did this in something recently. Trying to remember which tool...

**Comment by nguy** [comment]
Addressed in PR #149
