### ISSUE TITLE
Field calculation

### ISSUE THREAD

**Issue by gamaanderson** [nguy/artview#164]
I had an idea of how to use python magic to allow calculation and display of fields in a easy and intuitive way. something like:

```
reflectivity *= 2
```

 Just wanted to register it here so I don't forget.

**Comment by nguy** [comment]
Interesting idea!

**Comment by gamaanderson** [comment]
I have it here [https://github.com/gamaanderson/artview/tree/radar_terminal]

I made a small (sound less video) to show the idea
https://www.youtube.com/watch?v=jXVg3g8cnck

**Comment by nguy** [comment]
That is pretty neat and seems like it could be relatively easy to implement?

**Comment by gamaanderson** [comment]
it use pretty depp [python magic](https://docs.python.org/2/reference/datamodel.html#special-method-names), but it is easy. The only thing I don't like is that we still depend on the system terminal, emulating one is more complicated.

**Comment by nguy** [comment]
I agree it's not perfect, but better than nothing for the time being. I guess the argument could be made either way: If the tools are in place, porting may be simpler OR if we get too many tools in place, then porting is going to be a pain. Hmmm.

**Comment by gamaanderson** [comment]
this was closed by PR #175
