### ISSUE TITLE
PyQt5

### ISSUE THREAD

**Issue by pfhein** [nguy/artview#168]
The latest version of Anaconda Python 2.7 installs PyQt5 not PyQt4.  I just ran across this helping a student install artview on their Mac laptop.  It installs but then it can not find PyQt4.  Changing the 4 to 5 unfortunately did not work.  Here is the error when importing PyQt5 instead of PyQt4.
<img width="493" alt="screen shot 2016-11-07 at 2 23 28 pm" src="https://cloud.githubusercontent.com/assets/11464779/20076950/952c6482-a4f7-11e6-8e60-e867fd5f7694.png">

**Comment by gamaanderson** [comment]
I have recently faced the same problem. 
My [master branch](https://github.com/gamaanderson/artview) is changed to support PyQt5, I'm not totally sure however how stable it is, would recommend nevertheless.

Merging this in the main project is problematic because of the extensive module re-structuration from PyQt4 to PyQt5. While we are working on this, I would suggest opening a branch PyQt5 in @nguy repository and add a notice in the readme.

**Comment by pfhein** [comment]
Thank you @gamaanderson!  This was a big surprise to me.  I am glad that you are on top of it.

**Comment by pfhein** [comment]
@gamaanderson - Unfortunately there are still issues.  I have not had chance to take a close look at it but here is error messages.
<img width="673" alt="screen shot 2016-11-08 at 3 45 18 pm" src="https://cloud.githubusercontent.com/assets/11464779/20124253/5c3da8ac-a5e2-11e6-830d-724aa6c51c91.png">

**Comment by gamaanderson** [comment]
It does not seems you have the correct files.
This should be the (line)[https://github.com/gamaanderson/artview/blob/master/artview/core/core.py#L208]. Please try to make a plane new install

**Comment by pfhein** [comment]
I had grabbed the zip file, so maybe that was a problem, and I did not clean out the old install.  I will try again.

**Comment by nguy** [comment]
I recently ran into this when I changed jobs and was setting my computer up.

Another work around is to downgrade your PyQt to PyQt4.
You can get a list of packages: `conda search pyqt`
And then use the info to install a version 4 distribution: `conda install pyqt=4.11.4`

I think this should work, but as @gamaanderson mentioned, we'll have to make the move eventually.

**Comment by nguy** [comment]
@pfhein @gamaanderson Where are we at on this issue?

**Comment by gamaanderson** [comment]
If I got the time, tomorow I will make a PR. This will be a high conflict PR, so if you have anything not publish you should present it, so I can solve any conflicts.

**Comment by nguy** [comment]
Okay, there is a PR implementing the small fix you pulled back and a lot of small pep8 maintenance. If you could just breeze through quick and verify, that would be great. I can then hold off any more changes until you address this issue. In the meantime, I'll try to start commenting on some posts to get an idea of what we should work on next.

**Comment by gamaanderson** [comment]
implemented in PR #171

**Comment by nguy** [comment]
Can this topic be closed? 
I've opened another issue #174 to address the lingering problem with Qt5 compatibility.

**Comment by pfhein** [comment]
Yes, it can be closed.  I will do it.

**Comment by nguy** [comment]
@pfhein I'd love to hear any issues you run across. Make sure PyQt4 is available on machines.
