### ISSUE TITLE
Readme Typo error  in install name artivew instead of artview

### ISSUE THREAD

**Issue by bibraj** [nguy/artview#210]
In Readme document, typo error in conda install
conda install -c jjhelmus artivew

artivew is present instead of artview

**Comment by nguy** [comment]
Hi @bibraj , I looked at the REAMDE and did not see this error. Are you talking about [this section](https://github.com/nguy/artview/blob/master/README.md#install)?

**Comment by swnesbitt** [comment]
I've run into this here https://github.com/nguy/artview/blob/cf57fb7df40ab30662d16b47a61164a40a37706f/INSTALL.rst

**Comment by bibraj** [comment]
Yes, it is in the install.rst

**Comment by swnesbitt** [comment]
I created a pull request here #211

**Comment by nguy** [comment]
Thanks for finding this @bibraj  and @swnesbitt, I've accepted the pull request.
