### ISSUE TITLE
AdvanceFileSelect not working

### ISSUE THREAD

**Issue by mustafaalicelik** [nguy/artview#219]
This lines from "artview.components.menu.Menu" :

  def AdvanceFileSelect(self, findex):
        '''Captures a selection and open file.'''
        if findex > (len(self.Vfilelist.value)-1):
            msg = "End of directory, cannot advance!"
            common.ShowWarning(msg)
            findex = (len(self.Vfilelist.value) - 1)
            return
        if findex < 0:
            msg = "Beginning of directory, must move forward!"
            common.ShowWarning(msg)
            findex = 0
            return
        self.fileindex = findex
        self.filename = self.Vfilelist.value[findex]
        self._openfile()

"Beginning of directory" is working but "End of directory" part is not working. What is wrong with these lines?

**Comment by gamaanderson** [comment]
what do you mean by not working? What exactly is happening?

**Comment by mustafaalicelik** [comment]
Nothing, it advance to the second file from dir. No warning msg shown. But in the first file it shows the warning msg "Beginning of the directory, must move forward".

**Comment by gamaanderson** [comment]
the "returns" are wrong, they should not be there --- and they have being wrong all the way. But this case should never be executed, since the buttons for it should not been enabled to begin with. I will eventually fix it, now that I got artview running in my new laptop.

**Comment by mustafaalicelik** [comment]
When I open a random file from dir and using left key to open prev file, the "Beginning of the directory, must move forward" msg occurs. When I use right key to open next file, its opening the first file in directory. I think its not indexing the directory correctly. It should understand the first and the last file right after opening file from a directory.

**Comment by gamaanderson** [comment]
in this case I presume there is an error in the filelist. Probably the same error we just talked about.

**Comment by gamaanderson** [comment]
@nguy do you have a windows PC running artview? Could you test if moving from files within a directory is working?
