### ISSUE TITLE
File version

### ISSUE THREAD

**Issue by pfhein** [nguy/artview#27]
The file 'version' is not found if one is starting artview.py outside of the source directory.

**Comment by gamaanderson** [comment]
I would choose to just comment lines 10 to 13, 47 and 48 in `parser.py`. This parser file is just auxiliary, it is not a main part of artview

**Comment by pfhein** [comment]
I have been adding the path to it.  Either way it will need to be fixed 
and I am not certain how.

**Comment by nguy** [comment]
If and when this becomes an installable package (by adding setup.py) this will become moot I believe.

**Comment by pfhein** [comment]
I think you are right.  Thanks.
