### ISSUE TITLE
Mouse selection events overrun

### ISSUE THREAD

**Issue by nguy** [nguy/artview#64]
With the tools, I've noticed that selecting one tool after another can cause some behavior that could effect the use of ARTView. For example in Zoom/Pan is selected and then ROI is selected the user can no longer select curved lines. Instead the image pans. This can be alleviated by resetting the default. 

Maybe a reset of the tools could be added or disconnecting mouse events before connecting for each tool.

**Comment by gamaanderson** [comment]
I have known of this for a while, but it never annoyed me, reset was all that I need. If you are to implement something, just be sure not to disconnect ROI, this is much better done by closing the roi window.

**Comment by nguy** [comment]
This was fixed in PR #66 with the addition of a reset of tools and not just reset to default.
