### ISSUE TITLE
Filename in Display

### ISSUE THREAD

**Issue by nguy** [nguy/artview#65]
@gamaanderson I want your opinion here. I need to bring the filename over from the menu (or Variable) class to the Display to assign in the new QLabel at top. Which do you think would be easiest?

I was thinking it may be as simple as passing a ```filename```  keyword to the ```plot_radar.py``` Display class?

**Comment by gamaanderson** [comment]
no, passing this kind of information must be done with a variable, but I also wouldn’t what to add a Vfilename. You could in theory smuggle it in radar, by

    radar = pyart.io.read(filename)
    radar.filename = filename

and then test

    if hasattr(radar, "filename"):
       print radar.filename

**Comment by gamaanderson** [comment]
But when one things get complicated, this is a signal that there is something wrong. In this case, artview is build around pyart, and pyart does not recognize the existence of files (Jonathan will say `Radar` is an abstract structure). Therefore ARTview in theory should follow the lead of py-ART and don't care about filename.

**Comment by gamaanderson** [comment]
Just to be clear, I'm just say why of this uncomfortable limitation, not because of the Vvariable being a limitation, but this limitation is showing a concept conflict. I would also want `Radar` to be more closely related to disc files

**Comment by nguy** [comment]
Consider it smuggled....for now.

**Comment by nguy** [comment]
Everyone okay if I close this issue? It can be reopened if future change is desired.

**Comment by gamaanderson** [comment]
ok, you may close it
