### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by gamaanderson** [nguy/artview#88]
I've realized that if we want user to take advantage of artview versatility we must first show them that versatility and give a starting point. I thing the best way of doing that is increasing the number of scripts and show they better, so I did it and also took some printscreens 

(https://github.com/gamaanderson/artview/blob/ng-gatefilter/SCRIPTS.md)

let me know what you think. And FYI this is build over the ng-gatefilter branch

**Comment by nguy** [comment]
These are great! I've been meaning to do that @gamaanderson  
I just officially added the gatefilter portion. Do you want to do a pull request with these and then we can link the documentation later?

Also, I like your comments about "share" versus "link". I would not be against changing the naming conventions in the code and labels to indicate this.

**Comment by gamaanderson** [comment]
Yes, scripts are kind of a free part of the code, so I have no problem with direct merges. I also don't have a problem with the documentation not having that images, they can be seen in github.

**Comment by nguy** [comment]
Alright scripts are merged!
