### ISSUE TITLE
Plugin for IO

### ISSUE THREAD

**Issue by gamaanderson** [nguy/artview#94]
Make plug-in for more advanced io operations. It must in any case have a tree view of directory. It could also have an optional cache of radar files.

**Comment by nguy** [comment]
Something that might be nice is to pop up a list of files in directory and click on a file to display the data.

**Comment by gamaanderson** [comment]
that is exactly what I mean, Qt has already specific tools for doing such.

**Comment by gamaanderson** [comment]
I have this implemented in a [branch](https://github.com/gamaanderson/artview/tree/treeview). Use the view script (`artview -s view`) to give it a look. Use double clicks to move between folders (.. for back) and open files and right-click for more options.

I named this AdvancedIO, but for now it is only useful for opening. I have no good idea of how to add the write part.

**Comment by nguy** [comment]
Closing issue since this was merged
